export { default as HomePage } from './home'
export { default as ProfilePage } from './profile'
export { default as SearchPage } from './search'
export { default as ManagePage } from './manage'
export { default as MessagesPage } from './messages'
